//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace QueNoSePaseBot.ServicioWebHorariosProximos {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicioWebHorariosProximosSoap", Namespace="http://serviciosWebSms.efibus.com.ar/")]
    public partial class ServicioWebHorariosProximos : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RecuperarHorarioProgramadoPorParadaOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecuperarHorarioProximoPorParadaOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecuperarHorarioParadaInteligenteAndroiOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecuperarHorarioInspectoresOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecuperarHorarioConInternoOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecuperarHorarioConInternoYEmpresaOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecuperarHorarioCuandoLlegaAndroidOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecuperarMarkesinaCuandoLlegaAndroidPorUserIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecuperarVersionDBSQLiteVigenteAndroidOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecuperarTodosPaisesAndroidOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecuperarTodasProvinciasPorPaisAndroidOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecuperarTodasCiudadesPorProvinciaAndroidOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecuperarUserIdPorCiudadAndroidOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecuperarHorarioCuandoLlegaDosAndroidOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecuperarLineasPorParadaYGruposOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServicioWebHorariosProximos() {
            this.Url = global::QueNoSePaseBot.Properties.Settings.Default.Bot_Application1_ar_com_efibus_servicioswebsms4_ServicioWebHorariosProximos;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RecuperarHorarioProgramadoPorParadaCompletedEventHandler RecuperarHorarioProgramadoPorParadaCompleted;
        
        /// <remarks/>
        public event RecuperarHorarioProximoPorParadaCompletedEventHandler RecuperarHorarioProximoPorParadaCompleted;
        
        /// <remarks/>
        public event RecuperarHorarioParadaInteligenteAndroiCompletedEventHandler RecuperarHorarioParadaInteligenteAndroiCompleted;
        
        /// <remarks/>
        public event RecuperarHorarioInspectoresCompletedEventHandler RecuperarHorarioInspectoresCompleted;
        
        /// <remarks/>
        public event RecuperarHorarioConInternoCompletedEventHandler RecuperarHorarioConInternoCompleted;
        
        /// <remarks/>
        public event RecuperarHorarioConInternoYEmpresaCompletedEventHandler RecuperarHorarioConInternoYEmpresaCompleted;
        
        /// <remarks/>
        public event RecuperarHorarioCuandoLlegaAndroidCompletedEventHandler RecuperarHorarioCuandoLlegaAndroidCompleted;
        
        /// <remarks/>
        public event RecuperarMarkesinaCuandoLlegaAndroidPorUserIdCompletedEventHandler RecuperarMarkesinaCuandoLlegaAndroidPorUserIdCompleted;
        
        /// <remarks/>
        public event RecuperarVersionDBSQLiteVigenteAndroidCompletedEventHandler RecuperarVersionDBSQLiteVigenteAndroidCompleted;
        
        /// <remarks/>
        public event RecuperarTodosPaisesAndroidCompletedEventHandler RecuperarTodosPaisesAndroidCompleted;
        
        /// <remarks/>
        public event RecuperarTodasProvinciasPorPaisAndroidCompletedEventHandler RecuperarTodasProvinciasPorPaisAndroidCompleted;
        
        /// <remarks/>
        public event RecuperarTodasCiudadesPorProvinciaAndroidCompletedEventHandler RecuperarTodasCiudadesPorProvinciaAndroidCompleted;
        
        /// <remarks/>
        public event RecuperarUserIdPorCiudadAndroidCompletedEventHandler RecuperarUserIdPorCiudadAndroidCompleted;
        
        /// <remarks/>
        public event RecuperarHorarioCuandoLlegaDosAndroidCompletedEventHandler RecuperarHorarioCuandoLlegaDosAndroidCompleted;
        
        /// <remarks/>
        public event RecuperarLineasPorParadaYGruposCompletedEventHandler RecuperarLineasPorParadaYGruposCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosWebSms.efibus.com.ar/RecuperarHorarioProgramadoPorParada", RequestNamespace="http://serviciosWebSms.efibus.com.ar/", ResponseNamespace="http://serviciosWebSms.efibus.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RecuperarHorarioProgramadoPorParada(string gatewayId, string dn, string source, string mensajeUsuario, string carrier, string applidId, string userId, string usuario, string clave, int codigoEmpresa) {
            object[] results = this.Invoke("RecuperarHorarioProgramadoPorParada", new object[] {
                        gatewayId,
                        dn,
                        source,
                        mensajeUsuario,
                        carrier,
                        applidId,
                        userId,
                        usuario,
                        clave,
                        codigoEmpresa});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RecuperarHorarioProgramadoPorParadaAsync(string gatewayId, string dn, string source, string mensajeUsuario, string carrier, string applidId, string userId, string usuario, string clave, int codigoEmpresa) {
            this.RecuperarHorarioProgramadoPorParadaAsync(gatewayId, dn, source, mensajeUsuario, carrier, applidId, userId, usuario, clave, codigoEmpresa, null);
        }
        
        /// <remarks/>
        public void RecuperarHorarioProgramadoPorParadaAsync(string gatewayId, string dn, string source, string mensajeUsuario, string carrier, string applidId, string userId, string usuario, string clave, int codigoEmpresa, object userState) {
            if ((this.RecuperarHorarioProgramadoPorParadaOperationCompleted == null)) {
                this.RecuperarHorarioProgramadoPorParadaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperarHorarioProgramadoPorParadaOperationCompleted);
            }
            this.InvokeAsync("RecuperarHorarioProgramadoPorParada", new object[] {
                        gatewayId,
                        dn,
                        source,
                        mensajeUsuario,
                        carrier,
                        applidId,
                        userId,
                        usuario,
                        clave,
                        codigoEmpresa}, this.RecuperarHorarioProgramadoPorParadaOperationCompleted, userState);
        }
        
        private void OnRecuperarHorarioProgramadoPorParadaOperationCompleted(object arg) {
            if ((this.RecuperarHorarioProgramadoPorParadaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperarHorarioProgramadoPorParadaCompleted(this, new RecuperarHorarioProgramadoPorParadaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosWebSms.efibus.com.ar/RecuperarHorarioProximoPorParada", RequestNamespace="http://serviciosWebSms.efibus.com.ar/", ResponseNamespace="http://serviciosWebSms.efibus.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RecuperarHorarioProximoPorParada(string identificadorParada, string userId) {
            object[] results = this.Invoke("RecuperarHorarioProximoPorParada", new object[] {
                        identificadorParada,
                        userId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RecuperarHorarioProximoPorParadaAsync(string identificadorParada, string userId) {
            this.RecuperarHorarioProximoPorParadaAsync(identificadorParada, userId, null);
        }
        
        /// <remarks/>
        public void RecuperarHorarioProximoPorParadaAsync(string identificadorParada, string userId, object userState) {
            if ((this.RecuperarHorarioProximoPorParadaOperationCompleted == null)) {
                this.RecuperarHorarioProximoPorParadaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperarHorarioProximoPorParadaOperationCompleted);
            }
            this.InvokeAsync("RecuperarHorarioProximoPorParada", new object[] {
                        identificadorParada,
                        userId}, this.RecuperarHorarioProximoPorParadaOperationCompleted, userState);
        }
        
        private void OnRecuperarHorarioProximoPorParadaOperationCompleted(object arg) {
            if ((this.RecuperarHorarioProximoPorParadaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperarHorarioProximoPorParadaCompleted(this, new RecuperarHorarioProximoPorParadaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosWebSms.efibus.com.ar/RecuperarHorarioParadaInteligenteAndroi", RequestNamespace="http://serviciosWebSms.efibus.com.ar/", ResponseNamespace="http://serviciosWebSms.efibus.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RecuperarHorarioParadaInteligenteAndroi(string identificadorParada, string userId, string usuario, string clave) {
            object[] results = this.Invoke("RecuperarHorarioParadaInteligenteAndroi", new object[] {
                        identificadorParada,
                        userId,
                        usuario,
                        clave});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RecuperarHorarioParadaInteligenteAndroiAsync(string identificadorParada, string userId, string usuario, string clave) {
            this.RecuperarHorarioParadaInteligenteAndroiAsync(identificadorParada, userId, usuario, clave, null);
        }
        
        /// <remarks/>
        public void RecuperarHorarioParadaInteligenteAndroiAsync(string identificadorParada, string userId, string usuario, string clave, object userState) {
            if ((this.RecuperarHorarioParadaInteligenteAndroiOperationCompleted == null)) {
                this.RecuperarHorarioParadaInteligenteAndroiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperarHorarioParadaInteligenteAndroiOperationCompleted);
            }
            this.InvokeAsync("RecuperarHorarioParadaInteligenteAndroi", new object[] {
                        identificadorParada,
                        userId,
                        usuario,
                        clave}, this.RecuperarHorarioParadaInteligenteAndroiOperationCompleted, userState);
        }
        
        private void OnRecuperarHorarioParadaInteligenteAndroiOperationCompleted(object arg) {
            if ((this.RecuperarHorarioParadaInteligenteAndroiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperarHorarioParadaInteligenteAndroiCompleted(this, new RecuperarHorarioParadaInteligenteAndroiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosWebSms.efibus.com.ar/RecuperarHorarioInspectores", RequestNamespace="http://serviciosWebSms.efibus.com.ar/", ResponseNamespace="http://serviciosWebSms.efibus.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RecuperarHorarioInspectores(string identificadorParada, string userId, string usuario, string clave) {
            object[] results = this.Invoke("RecuperarHorarioInspectores", new object[] {
                        identificadorParada,
                        userId,
                        usuario,
                        clave});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RecuperarHorarioInspectoresAsync(string identificadorParada, string userId, string usuario, string clave) {
            this.RecuperarHorarioInspectoresAsync(identificadorParada, userId, usuario, clave, null);
        }
        
        /// <remarks/>
        public void RecuperarHorarioInspectoresAsync(string identificadorParada, string userId, string usuario, string clave, object userState) {
            if ((this.RecuperarHorarioInspectoresOperationCompleted == null)) {
                this.RecuperarHorarioInspectoresOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperarHorarioInspectoresOperationCompleted);
            }
            this.InvokeAsync("RecuperarHorarioInspectores", new object[] {
                        identificadorParada,
                        userId,
                        usuario,
                        clave}, this.RecuperarHorarioInspectoresOperationCompleted, userState);
        }
        
        private void OnRecuperarHorarioInspectoresOperationCompleted(object arg) {
            if ((this.RecuperarHorarioInspectoresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperarHorarioInspectoresCompleted(this, new RecuperarHorarioInspectoresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosWebSms.efibus.com.ar/RecuperarHorarioConInterno", RequestNamespace="http://serviciosWebSms.efibus.com.ar/", ResponseNamespace="http://serviciosWebSms.efibus.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RecuperarHorarioConInterno(string identificadorParada, string userId, string clave) {
            object[] results = this.Invoke("RecuperarHorarioConInterno", new object[] {
                        identificadorParada,
                        userId,
                        clave});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RecuperarHorarioConInternoAsync(string identificadorParada, string userId, string clave) {
            this.RecuperarHorarioConInternoAsync(identificadorParada, userId, clave, null);
        }
        
        /// <remarks/>
        public void RecuperarHorarioConInternoAsync(string identificadorParada, string userId, string clave, object userState) {
            if ((this.RecuperarHorarioConInternoOperationCompleted == null)) {
                this.RecuperarHorarioConInternoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperarHorarioConInternoOperationCompleted);
            }
            this.InvokeAsync("RecuperarHorarioConInterno", new object[] {
                        identificadorParada,
                        userId,
                        clave}, this.RecuperarHorarioConInternoOperationCompleted, userState);
        }
        
        private void OnRecuperarHorarioConInternoOperationCompleted(object arg) {
            if ((this.RecuperarHorarioConInternoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperarHorarioConInternoCompleted(this, new RecuperarHorarioConInternoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosWebSms.efibus.com.ar/RecuperarHorarioConInternoYEmpresa", RequestNamespace="http://serviciosWebSms.efibus.com.ar/", ResponseNamespace="http://serviciosWebSms.efibus.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RecuperarHorarioConInternoYEmpresa(string identificadorParada, string userId, string clave, int codigoLineaGrupo) {
            object[] results = this.Invoke("RecuperarHorarioConInternoYEmpresa", new object[] {
                        identificadorParada,
                        userId,
                        clave,
                        codigoLineaGrupo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RecuperarHorarioConInternoYEmpresaAsync(string identificadorParada, string userId, string clave, int codigoLineaGrupo) {
            this.RecuperarHorarioConInternoYEmpresaAsync(identificadorParada, userId, clave, codigoLineaGrupo, null);
        }
        
        /// <remarks/>
        public void RecuperarHorarioConInternoYEmpresaAsync(string identificadorParada, string userId, string clave, int codigoLineaGrupo, object userState) {
            if ((this.RecuperarHorarioConInternoYEmpresaOperationCompleted == null)) {
                this.RecuperarHorarioConInternoYEmpresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperarHorarioConInternoYEmpresaOperationCompleted);
            }
            this.InvokeAsync("RecuperarHorarioConInternoYEmpresa", new object[] {
                        identificadorParada,
                        userId,
                        clave,
                        codigoLineaGrupo}, this.RecuperarHorarioConInternoYEmpresaOperationCompleted, userState);
        }
        
        private void OnRecuperarHorarioConInternoYEmpresaOperationCompleted(object arg) {
            if ((this.RecuperarHorarioConInternoYEmpresaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperarHorarioConInternoYEmpresaCompleted(this, new RecuperarHorarioConInternoYEmpresaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosWebSms.efibus.com.ar/RecuperarHorarioCuandoLlegaAndroid", RequestNamespace="http://serviciosWebSms.efibus.com.ar/", ResponseNamespace="http://serviciosWebSms.efibus.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RecuperarHorarioCuandoLlegaAndroid(string identificadorParada, string userId, string descripcionLinea, string usuario, string clave, string codigoLineaGrupo) {
            object[] results = this.Invoke("RecuperarHorarioCuandoLlegaAndroid", new object[] {
                        identificadorParada,
                        userId,
                        descripcionLinea,
                        usuario,
                        clave,
                        codigoLineaGrupo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RecuperarHorarioCuandoLlegaAndroidAsync(string identificadorParada, string userId, string descripcionLinea, string usuario, string clave, string codigoLineaGrupo) {
            this.RecuperarHorarioCuandoLlegaAndroidAsync(identificadorParada, userId, descripcionLinea, usuario, clave, codigoLineaGrupo, null);
        }
        
        /// <remarks/>
        public void RecuperarHorarioCuandoLlegaAndroidAsync(string identificadorParada, string userId, string descripcionLinea, string usuario, string clave, string codigoLineaGrupo, object userState) {
            if ((this.RecuperarHorarioCuandoLlegaAndroidOperationCompleted == null)) {
                this.RecuperarHorarioCuandoLlegaAndroidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperarHorarioCuandoLlegaAndroidOperationCompleted);
            }
            this.InvokeAsync("RecuperarHorarioCuandoLlegaAndroid", new object[] {
                        identificadorParada,
                        userId,
                        descripcionLinea,
                        usuario,
                        clave,
                        codigoLineaGrupo}, this.RecuperarHorarioCuandoLlegaAndroidOperationCompleted, userState);
        }
        
        private void OnRecuperarHorarioCuandoLlegaAndroidOperationCompleted(object arg) {
            if ((this.RecuperarHorarioCuandoLlegaAndroidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperarHorarioCuandoLlegaAndroidCompleted(this, new RecuperarHorarioCuandoLlegaAndroidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosWebSms.efibus.com.ar/RecuperarMarkesinaCuandoLlegaAndroidPorUserI" +
            "d", RequestNamespace="http://serviciosWebSms.efibus.com.ar/", ResponseNamespace="http://serviciosWebSms.efibus.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RecuperarMarkesinaCuandoLlegaAndroidPorUserId(string userId, string usuario, string clave) {
            object[] results = this.Invoke("RecuperarMarkesinaCuandoLlegaAndroidPorUserId", new object[] {
                        userId,
                        usuario,
                        clave});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RecuperarMarkesinaCuandoLlegaAndroidPorUserIdAsync(string userId, string usuario, string clave) {
            this.RecuperarMarkesinaCuandoLlegaAndroidPorUserIdAsync(userId, usuario, clave, null);
        }
        
        /// <remarks/>
        public void RecuperarMarkesinaCuandoLlegaAndroidPorUserIdAsync(string userId, string usuario, string clave, object userState) {
            if ((this.RecuperarMarkesinaCuandoLlegaAndroidPorUserIdOperationCompleted == null)) {
                this.RecuperarMarkesinaCuandoLlegaAndroidPorUserIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperarMarkesinaCuandoLlegaAndroidPorUserIdOperationCompleted);
            }
            this.InvokeAsync("RecuperarMarkesinaCuandoLlegaAndroidPorUserId", new object[] {
                        userId,
                        usuario,
                        clave}, this.RecuperarMarkesinaCuandoLlegaAndroidPorUserIdOperationCompleted, userState);
        }
        
        private void OnRecuperarMarkesinaCuandoLlegaAndroidPorUserIdOperationCompleted(object arg) {
            if ((this.RecuperarMarkesinaCuandoLlegaAndroidPorUserIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperarMarkesinaCuandoLlegaAndroidPorUserIdCompleted(this, new RecuperarMarkesinaCuandoLlegaAndroidPorUserIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosWebSms.efibus.com.ar/RecuperarVersionDBSQLiteVigenteAndroid", RequestNamespace="http://serviciosWebSms.efibus.com.ar/", ResponseNamespace="http://serviciosWebSms.efibus.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RecuperarVersionDBSQLiteVigenteAndroid(string userId, string usuario, string clave) {
            object[] results = this.Invoke("RecuperarVersionDBSQLiteVigenteAndroid", new object[] {
                        userId,
                        usuario,
                        clave});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RecuperarVersionDBSQLiteVigenteAndroidAsync(string userId, string usuario, string clave) {
            this.RecuperarVersionDBSQLiteVigenteAndroidAsync(userId, usuario, clave, null);
        }
        
        /// <remarks/>
        public void RecuperarVersionDBSQLiteVigenteAndroidAsync(string userId, string usuario, string clave, object userState) {
            if ((this.RecuperarVersionDBSQLiteVigenteAndroidOperationCompleted == null)) {
                this.RecuperarVersionDBSQLiteVigenteAndroidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperarVersionDBSQLiteVigenteAndroidOperationCompleted);
            }
            this.InvokeAsync("RecuperarVersionDBSQLiteVigenteAndroid", new object[] {
                        userId,
                        usuario,
                        clave}, this.RecuperarVersionDBSQLiteVigenteAndroidOperationCompleted, userState);
        }
        
        private void OnRecuperarVersionDBSQLiteVigenteAndroidOperationCompleted(object arg) {
            if ((this.RecuperarVersionDBSQLiteVigenteAndroidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperarVersionDBSQLiteVigenteAndroidCompleted(this, new RecuperarVersionDBSQLiteVigenteAndroidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosWebSms.efibus.com.ar/RecuperarTodosPaisesAndroid", RequestNamespace="http://serviciosWebSms.efibus.com.ar/", ResponseNamespace="http://serviciosWebSms.efibus.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RecuperarTodosPaisesAndroid(string usuario, string clave) {
            object[] results = this.Invoke("RecuperarTodosPaisesAndroid", new object[] {
                        usuario,
                        clave});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RecuperarTodosPaisesAndroidAsync(string usuario, string clave) {
            this.RecuperarTodosPaisesAndroidAsync(usuario, clave, null);
        }
        
        /// <remarks/>
        public void RecuperarTodosPaisesAndroidAsync(string usuario, string clave, object userState) {
            if ((this.RecuperarTodosPaisesAndroidOperationCompleted == null)) {
                this.RecuperarTodosPaisesAndroidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperarTodosPaisesAndroidOperationCompleted);
            }
            this.InvokeAsync("RecuperarTodosPaisesAndroid", new object[] {
                        usuario,
                        clave}, this.RecuperarTodosPaisesAndroidOperationCompleted, userState);
        }
        
        private void OnRecuperarTodosPaisesAndroidOperationCompleted(object arg) {
            if ((this.RecuperarTodosPaisesAndroidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperarTodosPaisesAndroidCompleted(this, new RecuperarTodosPaisesAndroidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosWebSms.efibus.com.ar/RecuperarTodasProvinciasPorPaisAndroid", RequestNamespace="http://serviciosWebSms.efibus.com.ar/", ResponseNamespace="http://serviciosWebSms.efibus.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RecuperarTodasProvinciasPorPaisAndroid(int codigoPais, string usuario, string clave) {
            object[] results = this.Invoke("RecuperarTodasProvinciasPorPaisAndroid", new object[] {
                        codigoPais,
                        usuario,
                        clave});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RecuperarTodasProvinciasPorPaisAndroidAsync(int codigoPais, string usuario, string clave) {
            this.RecuperarTodasProvinciasPorPaisAndroidAsync(codigoPais, usuario, clave, null);
        }
        
        /// <remarks/>
        public void RecuperarTodasProvinciasPorPaisAndroidAsync(int codigoPais, string usuario, string clave, object userState) {
            if ((this.RecuperarTodasProvinciasPorPaisAndroidOperationCompleted == null)) {
                this.RecuperarTodasProvinciasPorPaisAndroidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperarTodasProvinciasPorPaisAndroidOperationCompleted);
            }
            this.InvokeAsync("RecuperarTodasProvinciasPorPaisAndroid", new object[] {
                        codigoPais,
                        usuario,
                        clave}, this.RecuperarTodasProvinciasPorPaisAndroidOperationCompleted, userState);
        }
        
        private void OnRecuperarTodasProvinciasPorPaisAndroidOperationCompleted(object arg) {
            if ((this.RecuperarTodasProvinciasPorPaisAndroidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperarTodasProvinciasPorPaisAndroidCompleted(this, new RecuperarTodasProvinciasPorPaisAndroidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosWebSms.efibus.com.ar/RecuperarTodasCiudadesPorProvinciaAndroid", RequestNamespace="http://serviciosWebSms.efibus.com.ar/", ResponseNamespace="http://serviciosWebSms.efibus.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RecuperarTodasCiudadesPorProvinciaAndroid(int codigoProvincia, string usuario, string clave) {
            object[] results = this.Invoke("RecuperarTodasCiudadesPorProvinciaAndroid", new object[] {
                        codigoProvincia,
                        usuario,
                        clave});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RecuperarTodasCiudadesPorProvinciaAndroidAsync(int codigoProvincia, string usuario, string clave) {
            this.RecuperarTodasCiudadesPorProvinciaAndroidAsync(codigoProvincia, usuario, clave, null);
        }
        
        /// <remarks/>
        public void RecuperarTodasCiudadesPorProvinciaAndroidAsync(int codigoProvincia, string usuario, string clave, object userState) {
            if ((this.RecuperarTodasCiudadesPorProvinciaAndroidOperationCompleted == null)) {
                this.RecuperarTodasCiudadesPorProvinciaAndroidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperarTodasCiudadesPorProvinciaAndroidOperationCompleted);
            }
            this.InvokeAsync("RecuperarTodasCiudadesPorProvinciaAndroid", new object[] {
                        codigoProvincia,
                        usuario,
                        clave}, this.RecuperarTodasCiudadesPorProvinciaAndroidOperationCompleted, userState);
        }
        
        private void OnRecuperarTodasCiudadesPorProvinciaAndroidOperationCompleted(object arg) {
            if ((this.RecuperarTodasCiudadesPorProvinciaAndroidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperarTodasCiudadesPorProvinciaAndroidCompleted(this, new RecuperarTodasCiudadesPorProvinciaAndroidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosWebSms.efibus.com.ar/RecuperarUserIdPorCiudadAndroid", RequestNamespace="http://serviciosWebSms.efibus.com.ar/", ResponseNamespace="http://serviciosWebSms.efibus.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RecuperarUserIdPorCiudadAndroid(int codigoCiudad, string usuario, string clave) {
            object[] results = this.Invoke("RecuperarUserIdPorCiudadAndroid", new object[] {
                        codigoCiudad,
                        usuario,
                        clave});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RecuperarUserIdPorCiudadAndroidAsync(int codigoCiudad, string usuario, string clave) {
            this.RecuperarUserIdPorCiudadAndroidAsync(codigoCiudad, usuario, clave, null);
        }
        
        /// <remarks/>
        public void RecuperarUserIdPorCiudadAndroidAsync(int codigoCiudad, string usuario, string clave, object userState) {
            if ((this.RecuperarUserIdPorCiudadAndroidOperationCompleted == null)) {
                this.RecuperarUserIdPorCiudadAndroidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperarUserIdPorCiudadAndroidOperationCompleted);
            }
            this.InvokeAsync("RecuperarUserIdPorCiudadAndroid", new object[] {
                        codigoCiudad,
                        usuario,
                        clave}, this.RecuperarUserIdPorCiudadAndroidOperationCompleted, userState);
        }
        
        private void OnRecuperarUserIdPorCiudadAndroidOperationCompleted(object arg) {
            if ((this.RecuperarUserIdPorCiudadAndroidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperarUserIdPorCiudadAndroidCompleted(this, new RecuperarUserIdPorCiudadAndroidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosWebSms.efibus.com.ar/RecuperarHorarioCuandoLlegaDosAndroid", RequestNamespace="http://serviciosWebSms.efibus.com.ar/", ResponseNamespace="http://serviciosWebSms.efibus.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RecuperarHorarioCuandoLlegaDosAndroid(string identificadorParada, string userId, string descripcionLinea, string usuario, string clave, string codigoLineaGrupo) {
            object[] results = this.Invoke("RecuperarHorarioCuandoLlegaDosAndroid", new object[] {
                        identificadorParada,
                        userId,
                        descripcionLinea,
                        usuario,
                        clave,
                        codigoLineaGrupo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RecuperarHorarioCuandoLlegaDosAndroidAsync(string identificadorParada, string userId, string descripcionLinea, string usuario, string clave, string codigoLineaGrupo) {
            this.RecuperarHorarioCuandoLlegaDosAndroidAsync(identificadorParada, userId, descripcionLinea, usuario, clave, codigoLineaGrupo, null);
        }
        
        /// <remarks/>
        public void RecuperarHorarioCuandoLlegaDosAndroidAsync(string identificadorParada, string userId, string descripcionLinea, string usuario, string clave, string codigoLineaGrupo, object userState) {
            if ((this.RecuperarHorarioCuandoLlegaDosAndroidOperationCompleted == null)) {
                this.RecuperarHorarioCuandoLlegaDosAndroidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperarHorarioCuandoLlegaDosAndroidOperationCompleted);
            }
            this.InvokeAsync("RecuperarHorarioCuandoLlegaDosAndroid", new object[] {
                        identificadorParada,
                        userId,
                        descripcionLinea,
                        usuario,
                        clave,
                        codigoLineaGrupo}, this.RecuperarHorarioCuandoLlegaDosAndroidOperationCompleted, userState);
        }
        
        private void OnRecuperarHorarioCuandoLlegaDosAndroidOperationCompleted(object arg) {
            if ((this.RecuperarHorarioCuandoLlegaDosAndroidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperarHorarioCuandoLlegaDosAndroidCompleted(this, new RecuperarHorarioCuandoLlegaDosAndroidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosWebSms.efibus.com.ar/RecuperarLineasPorParadaYGrupos", RequestNamespace="http://serviciosWebSms.efibus.com.ar/", ResponseNamespace="http://serviciosWebSms.efibus.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RecuperarLineasPorParadaYGrupos(string identificadorParada, string userId, string clave, string stringGrupos) {
            object[] results = this.Invoke("RecuperarLineasPorParadaYGrupos", new object[] {
                        identificadorParada,
                        userId,
                        clave,
                        stringGrupos});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RecuperarLineasPorParadaYGruposAsync(string identificadorParada, string userId, string clave, string stringGrupos) {
            this.RecuperarLineasPorParadaYGruposAsync(identificadorParada, userId, clave, stringGrupos, null);
        }
        
        /// <remarks/>
        public void RecuperarLineasPorParadaYGruposAsync(string identificadorParada, string userId, string clave, string stringGrupos, object userState) {
            if ((this.RecuperarLineasPorParadaYGruposOperationCompleted == null)) {
                this.RecuperarLineasPorParadaYGruposOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperarLineasPorParadaYGruposOperationCompleted);
            }
            this.InvokeAsync("RecuperarLineasPorParadaYGrupos", new object[] {
                        identificadorParada,
                        userId,
                        clave,
                        stringGrupos}, this.RecuperarLineasPorParadaYGruposOperationCompleted, userState);
        }
        
        private void OnRecuperarLineasPorParadaYGruposOperationCompleted(object arg) {
            if ((this.RecuperarLineasPorParadaYGruposCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperarLineasPorParadaYGruposCompleted(this, new RecuperarLineasPorParadaYGruposCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void RecuperarHorarioProgramadoPorParadaCompletedEventHandler(object sender, RecuperarHorarioProgramadoPorParadaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperarHorarioProgramadoPorParadaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperarHorarioProgramadoPorParadaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void RecuperarHorarioProximoPorParadaCompletedEventHandler(object sender, RecuperarHorarioProximoPorParadaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperarHorarioProximoPorParadaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperarHorarioProximoPorParadaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void RecuperarHorarioParadaInteligenteAndroiCompletedEventHandler(object sender, RecuperarHorarioParadaInteligenteAndroiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperarHorarioParadaInteligenteAndroiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperarHorarioParadaInteligenteAndroiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void RecuperarHorarioInspectoresCompletedEventHandler(object sender, RecuperarHorarioInspectoresCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperarHorarioInspectoresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperarHorarioInspectoresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void RecuperarHorarioConInternoCompletedEventHandler(object sender, RecuperarHorarioConInternoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperarHorarioConInternoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperarHorarioConInternoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void RecuperarHorarioConInternoYEmpresaCompletedEventHandler(object sender, RecuperarHorarioConInternoYEmpresaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperarHorarioConInternoYEmpresaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperarHorarioConInternoYEmpresaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void RecuperarHorarioCuandoLlegaAndroidCompletedEventHandler(object sender, RecuperarHorarioCuandoLlegaAndroidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperarHorarioCuandoLlegaAndroidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperarHorarioCuandoLlegaAndroidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void RecuperarMarkesinaCuandoLlegaAndroidPorUserIdCompletedEventHandler(object sender, RecuperarMarkesinaCuandoLlegaAndroidPorUserIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperarMarkesinaCuandoLlegaAndroidPorUserIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperarMarkesinaCuandoLlegaAndroidPorUserIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void RecuperarVersionDBSQLiteVigenteAndroidCompletedEventHandler(object sender, RecuperarVersionDBSQLiteVigenteAndroidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperarVersionDBSQLiteVigenteAndroidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperarVersionDBSQLiteVigenteAndroidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void RecuperarTodosPaisesAndroidCompletedEventHandler(object sender, RecuperarTodosPaisesAndroidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperarTodosPaisesAndroidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperarTodosPaisesAndroidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void RecuperarTodasProvinciasPorPaisAndroidCompletedEventHandler(object sender, RecuperarTodasProvinciasPorPaisAndroidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperarTodasProvinciasPorPaisAndroidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperarTodasProvinciasPorPaisAndroidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void RecuperarTodasCiudadesPorProvinciaAndroidCompletedEventHandler(object sender, RecuperarTodasCiudadesPorProvinciaAndroidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperarTodasCiudadesPorProvinciaAndroidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperarTodasCiudadesPorProvinciaAndroidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void RecuperarUserIdPorCiudadAndroidCompletedEventHandler(object sender, RecuperarUserIdPorCiudadAndroidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperarUserIdPorCiudadAndroidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperarUserIdPorCiudadAndroidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void RecuperarHorarioCuandoLlegaDosAndroidCompletedEventHandler(object sender, RecuperarHorarioCuandoLlegaDosAndroidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperarHorarioCuandoLlegaDosAndroidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperarHorarioCuandoLlegaDosAndroidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void RecuperarLineasPorParadaYGruposCompletedEventHandler(object sender, RecuperarLineasPorParadaYGruposCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperarLineasPorParadaYGruposCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperarLineasPorParadaYGruposCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591